USE master
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='DB_EXEMPLO')
BEGIN
	ALTER DATABASE DB_EXEMPLO SET  SINGLE_USER WITH ROLLBACK IMMEDIATE

	DROP DATABASE DB_EXEMPLO
END
GO
CREATE DATABASE DB_EXEMPLO
GO

USE DB_EXEMPLO

CREATE TABLE CLIENTE 
(
	ID_CLIENTE INT IDENTITY PRIMARY KEY, 
	NOME_CLIENTE VARCHAR(50)
)

INSERT INTO CLIENTE 
VALUES ('ADÃO'), 
	('EVA'), 
	('CAIM'), 
	('ABEL')

SELECT * FROM CLIENTE