<?xml version="1.0" encoding="utf-8"?><Database Name="DB_EXEMPLO" Class="ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=DB_EXEMPLO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_EXEMPLOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CLIENTE" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="ID_CLIENTE" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOME_CLIENTE" Member="Nome" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>