<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="_005_DataSource.WebForm1" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="GENREID" 
            DataSourceID="OracleDataSource" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <Columns>
                <asp:BoundField DataField="GENREID" HeaderText="GENREID" ReadOnly="True" 
                    SortExpression="GENREID" />
                <asp:BoundField DataField="NAME" HeaderText="NAME" SortExpression="NAME" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="OracleDataSource" runat="server" 
            ConnectionString="DATA SOURCE=127.0.0.1/ORCL;PASSWORD=p4ssw0rd;USER ID=CHINOOK" 
            ProviderName="Oracle.DataAccess.Client" 
            SelectCommand="SELECT * FROM &quot;GENRE&quot;" 
            DeleteCommand="DELETE FROM &quot;GENRE&quot; WHERE &quot;GENREID&quot; = :GENREID" 
            InsertCommand="INSERT INTO &quot;GENRE&quot; (&quot;GENREID&quot;, &quot;NAME&quot;) VALUES (:GENREID, :NAME)" 
            UpdateCommand="UPDATE &quot;GENRE&quot; SET &quot;NAME&quot; = :NAME WHERE &quot;GENREID&quot; = :GENREID">
            <DeleteParameters>
                <asp:Parameter Name="GENREID" Type="Decimal" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="GENREID" Type="Decimal" />
                <asp:Parameter Name="NAME" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="NAME" Type="String" />
                <asp:Parameter Name="GENREID" Type="Decimal" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>
