//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _003_ConsomeWCFAssincrono.ProxyGenero {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genero", Namespace="http://schemas.datacontract.org/2004/07/_001_WCF", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Genero : _003_ConsomeWCFAssincrono.ProxyGenero.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.Genero))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.Genero))]
    public partial class EntityObject : _003_ConsomeWCFAssincrono.ProxyGenero.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _003_ConsomeWCFAssincrono.ProxyGenero.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _003_ConsomeWCFAssincrono.ProxyGenero.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private _003_ConsomeWCFAssincrono.ProxyGenero.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public _003_ConsomeWCFAssincrono.ProxyGenero.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.Genero[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.Genero))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(_003_ConsomeWCFAssincrono.ProxyGenero.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyGenero.IGeneroService")]
    public interface IGeneroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneroService/GetFirst10", ReplyAction="http://tempuri.org/IGeneroService/GetFirst10Response")]
        _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] GetFirst10();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGeneroService/GetFirst10", ReplyAction="http://tempuri.org/IGeneroService/GetFirst10Response")]
        System.IAsyncResult BeginGetFirst10(System.AsyncCallback callback, object asyncState);
        
        _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] EndGetFirst10(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneroService/GetById", ReplyAction="http://tempuri.org/IGeneroService/GetByIdResponse")]
        _003_ConsomeWCFAssincrono.ProxyGenero.Genero GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IGeneroService/GetById", ReplyAction="http://tempuri.org/IGeneroService/GetByIdResponse")]
        System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState);
        
        _003_ConsomeWCFAssincrono.ProxyGenero.Genero EndGetById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneroServiceChannel : _003_ConsomeWCFAssincrono.ProxyGenero.IGeneroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFirst10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFirst10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_003_ConsomeWCFAssincrono.ProxyGenero.Genero[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_003_ConsomeWCFAssincrono.ProxyGenero.Genero)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneroServiceClient : System.ServiceModel.ClientBase<_003_ConsomeWCFAssincrono.ProxyGenero.IGeneroService>, _003_ConsomeWCFAssincrono.ProxyGenero.IGeneroService {
        
        private BeginOperationDelegate onBeginGetFirst10Delegate;
        
        private EndOperationDelegate onEndGetFirst10Delegate;
        
        private System.Threading.SendOrPostCallback onGetFirst10CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetByIdDelegate;
        
        private EndOperationDelegate onEndGetByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetByIdCompletedDelegate;
        
        public GeneroServiceClient() {
        }
        
        public GeneroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetFirst10CompletedEventArgs> GetFirst10Completed;
        
        public event System.EventHandler<GetByIdCompletedEventArgs> GetByIdCompleted;
        
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] GetFirst10() {
            return base.Channel.GetFirst10();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFirst10(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFirst10(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] EndGetFirst10(System.IAsyncResult result) {
            return base.Channel.EndGetFirst10(result);
        }
        
        private System.IAsyncResult OnBeginGetFirst10(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetFirst10(callback, asyncState);
        }
        
        private object[] OnEndGetFirst10(System.IAsyncResult result) {
            _003_ConsomeWCFAssincrono.ProxyGenero.Genero[] retVal = this.EndGetFirst10(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFirst10Completed(object state) {
            if ((this.GetFirst10Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFirst10Completed(this, new GetFirst10CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFirst10Async() {
            this.GetFirst10Async(null);
        }
        
        public void GetFirst10Async(object userState) {
            if ((this.onBeginGetFirst10Delegate == null)) {
                this.onBeginGetFirst10Delegate = new BeginOperationDelegate(this.OnBeginGetFirst10);
            }
            if ((this.onEndGetFirst10Delegate == null)) {
                this.onEndGetFirst10Delegate = new EndOperationDelegate(this.OnEndGetFirst10);
            }
            if ((this.onGetFirst10CompletedDelegate == null)) {
                this.onGetFirst10CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFirst10Completed);
            }
            base.InvokeAsync(this.onBeginGetFirst10Delegate, null, this.onEndGetFirst10Delegate, this.onGetFirst10CompletedDelegate, userState);
        }
        
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _003_ConsomeWCFAssincrono.ProxyGenero.Genero EndGetById(System.IAsyncResult result) {
            return base.Channel.EndGetById(result);
        }
        
        private System.IAsyncResult OnBeginGetById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BeginGetById(id, callback, asyncState);
        }
        
        private object[] OnEndGetById(System.IAsyncResult result) {
            _003_ConsomeWCFAssincrono.ProxyGenero.Genero retVal = this.EndGetById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetByIdCompleted(object state) {
            if ((this.GetByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetByIdAsync(int id) {
            this.GetByIdAsync(id, null);
        }
        
        public void GetByIdAsync(int id, object userState) {
            if ((this.onBeginGetByIdDelegate == null)) {
                this.onBeginGetByIdDelegate = new BeginOperationDelegate(this.OnBeginGetById);
            }
            if ((this.onEndGetByIdDelegate == null)) {
                this.onEndGetByIdDelegate = new EndOperationDelegate(this.OnEndGetById);
            }
            if ((this.onGetByIdCompletedDelegate == null)) {
                this.onGetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetByIdDelegate, new object[] {
                        id}, this.onEndGetByIdDelegate, this.onGetByIdCompletedDelegate, userState);
        }
    }
}
